# Generated by Django 5.0.7 on 2024-08-06 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ('date', '-pk')},
        ),
    ]
